### ISSUE TITLE
Only replacing destination file character by character

### ISSUE THREAD

**Issue by densk1** [GoogleCloudPlatform/berglas#142]
I have the following step in a `cloudbuild.yaml` file. It replaces the development `config.js` file with a production config file.

The production config file has fewer lines than the development one. When Berglas is overwriting the destination file, it appears to overwrite each character from the new file, until it runs out of characters.

This is leaving my updated config file corrupted because it is not syntactically correct.

```
steps:
  - id: get-secrets
    name: gcr.io/berglas/berglas
    env:
      - 'CONFIG_FILE=sm://$PROJECT_ID/config-production?destination=src/config/config.js'
    args: ["exec", "--", "/bin/sh"]
```
**Expectation**
My expectation is that the whole file would be overwritten.

**Current Workaround**
I have added multiple empty lines to the top of the production config file.
