### ISSUE TITLE
Possibility to use injected secrets in command args within k8s deployment yaml

### ISSUE THREAD

**Issue by bayerlse** [GoogleCloudPlatform/berglas#143]
Hey there!

I have following setup:

My run command for the k8s application needs to have the secrets passed via command line arg

So if i have an env prepared like this:

```yaml
env:
  - name: MY_SECRET
    value: "sm://{{.projectId}}/my-secret"
```
And then defining the command with args underneath it:

```yaml
command: ["java"]
args: ["-jar", "target/app-1.0.jar", "-secret", "$(MY_SECRET)"]
```

It doesnt inject the secrets from Google Secrets Manager.

If I would do just:

```yaml
command: ["printenv"]
args: ["MY_SECRET"]
```

it works.

Do you have any suggestions?

Thanks!
