### ISSUE TITLE
Unable to use the mutation webhook method with kubernetes 1.21.5 and admissionregistration.k8s.io/v1 on GKE

### ISSUE THREAD

**Issue by martinlevesque** [GoogleCloudPlatform/berglas#177]
Hi everyone,

We have been using the following way to use berglas with mutation webhook https://github.com/GoogleCloudPlatform/berglas/tree/main/examples/kubernetes with admissionregistration.k8s.io/v1beta1 mutation webhook with success. One important note is that `admissionregistration.k8s.io/v1beta1` will get deprecated in Kubernetes 1.22 in favor of `admissionregistration.k8s.io/v1`.

As soon as we try to use `admissionregistration.k8s.io/v1` we are no more able to have it work using the go function here https://github.com/GoogleCloudPlatform/berglas/tree/main/examples/kubernetes

From the gcloud function everything looks working, as we see logs such as:

```
2022/01/11 19:29:41 [DEBUG] json patch for request 82e6db3e-7e4e-499c-ae83-dcd622ce168b: [{"op":"add","path":"/spec/volumes/1","value":{"name":"berglas-bin","emptyDir":{"medium":"Memory"}}},{"op":"add","path":"/spec/initContainers","value":[{"name":"copy-berglas-bin","image":"us-docker.pkg.dev/berglas/berglas/berglas:latest","command":["sh","-c","cp /bin/berglas /berglas/bin/"],"resources":{},"volumeMounts":[{"name":"berglas-bin","mountPath":"/berglas/bin/"}],"imagePullPolicy":"IfNotPresent"}]},{"op":"replace","path":"/spec/containers/0/command/0","value":"/berglas/bin/berglas"},{"op":"add","path":"/spec/containers/0/args","value":["exec","--","/bin/envserver"]},{"op":"add","path":"/spec/containers/0/volumeMounts/1","value":{"name":"berglas-bin","readOnly":true,"mountPath":"/berglas/bin/"}}]
```

However the POD does not start and I can see the following POD status error:

```
- lastTransitionTime: "2022-01-12T16:25:42Z"
    lastUpdateTime: "2022-01-12T16:25:42Z"
    message: 'Internal error occurred: failed calling webhook "berglas-webhook.cloud.google.com":
      expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got
      /, Kind='
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

The webhook file I am using:

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: berglas-webhook
  labels:
    app: berglas-webhook
    kind: mutator

webhooks:
- name: berglas-webhook.cloud.google.com
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    url: https://northamerica-northeast1-PROJECT-ID.cloudfunctions.net/berglas-secrets-webhook
    caBundle: ""
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  sideEffects: NoneOnDryRun
  
```

I also tried to update 2 packages (berglas and kubewebhook) in go.mod but I am getting the same behavior:

```
module hello

go 1.13

require (
    github.com/GoogleCloudPlatform/berglas v0.6.2
    github.com/slok/kubewebhook/v2 v2.1.0
    k8s.io/api v0.18.6
    k8s.io/apimachinery v0.18.6
)
```

Any ideas what should be changed to make it work with `admissionregistration.k8s.io/v1` ?

Thanks!

##

- Related issue reporting the same issue: https://github.com/GoogleCloudPlatform/berglas/issues/162
