### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by rahulracker7539** [GoogleCloudPlatform/berglas#265]
Hi Everyone,

I have deployed the mutating webhook having url endpoint hitting to cloud run endpoint but when am trying to deploy the sample pod/deployment having env. value to refer to secret manager then am getting below error.

```
rahu7539@AAD-5ZTF3M3:/mnt/c/Users/rahu7539/git/sandbox/secret_manager$ kubectl apply -f sample.yaml
Error from server (InternalError): error when creating "sample.yaml": Internal error occurred: failed calling webhook "berglas-webhook.cloud.google.com": failed to call webhook: yaml: line 3: **mapping values are not allowed in this context**
```

**sample.yaml**

```
apiVersion: v1
kind: Pod
metadata:
  name: envserver
  labels:
    app: envserver
spec:
  serviceAccountName: envserver
  containers:
    - name: envserver
      image: sethvargo/envserver
      imagePullPolicy: Always
      command: ["/bin/envserver"]
      env:
        # This is an example using Berglas with Secret Manager storage.
        - name: API_KEY
          value: sm://<project-id>/api-key
```
          
        
**webhook.yaml**

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: berglas-webhook
  labels:
    app: berglas-webhook
    kind: mutator
webhooks:
- name: berglas-webhook.cloud.google.com
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: NoneOnDryRun
  clientConfig:
    url: <url>
    caBundle: ""
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
```
    
Cloud run is allowed to accept the unauthenticated invocations and looking at the logs I see 200 post request successful whenever am trying to deploy the sample.yaml application.

2024-07-11 14:54:40.819 BST
POST200 184 B 2 ms kube-apiserver-admission  https://<url>.a.run.app/?timeout=10s 

I can also confirm that am using workload identity in the sample pod and it has enough permission.

GKE cluster version - 1.29.4-gke.1043004 
have used golang 1.20 version to build the docker images
